server:
  port: 9005

spring:
  application:
    name: WEB-APP



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://macscratchdeploy-production.up.railway.app/eureka/
  instance:
    hostname: app0
